app/models.py
from datetime import datetime

from marshmallow_sqlalchemy import SQLAlchemyAutoSchema

from app import db


def add_schema(cls):
    class Schema(SQLAlchemyAutoSchema):
        class Meta:
            model = cls
            load_instance = True

    cls.Schema = Schema
    return cls


class BaseModel(db.Model):
    __abstract__ = True

    def create(self):
        db.session.add(self)
        db.session.commit()
        return self

    def __repr__(self):
        return '{}'.format(self.id)


@add_schema
class Trade(BaseModel):
    __tablename__ = 'trades'

    id = db.Column(db.Integer, primary_key=True)
    symbol = db.Column(db.String(3), nullable=False)
    matched_price = db.Column(db.Float, nullable=False)
    average_price = db.Column(db.Float, nullable=True)
    net_price = db.Column(db.Float, nullable=False)
    shares = db.Column(db.Float, nullable=False)
    order = db.Column(db.Integer, default=0)
    date = db.Column(db.DateTime, default=datetime.utcnow(), onupdate=datetime.utcnow())

    def dump(self):
        return __class__.Schema().dump(self)

    @staticmethod
    def load(data):
        return __class__.Schema().load(data, session=db.session)


@add_schema
class Stock(BaseModel):
    __tablename__ = 'stocks'

    id = db.Column(db.Integer, primary_key=True)
    symbol = db.Column(db.String(3), unique=Trade)
    price = db.Column(db.Float, default=0)
    shares = db.Column(db.Float, default=0)
    ratio = db.Column(db.Float, default=0.2)
    freeroll = db.Column(db.Boolean, default=False)

    def dump(self):
        return __class__.Schema().dump(self)

    @staticmethod
    def load(data):
        return __class__.Schema().load(data, session=db.session)

app/home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, FloatField, SubmitField
from wtforms.validators import data_required, optional

from app.utils.wtf_utils import InlineButtonWidget


class TradeForm(FlaskForm):
    symbol = StringField('Symbol', validators=[data_required()], render_kw={'placeholder': 'Symbol'})
    price = FloatField('Price', validators=[data_required()], render_kw={'placeholder': 'Price'})
    shares = FloatField('Shares', validators=[data_required()], render_kw={'placeholder': 'Shares'})
    profit_margin = FloatField('Profit Margin', validators=[optional()],
                               render_kw={'placeholder': 'Profit Margin'})

    bt_sell = SubmitField('SELL', widget=InlineButtonWidget(class_="btn btn-danger pull-right"),
                          render_kw={'name': 'action', 'style': 'margin-left : 8px;'})
    bt_buy = SubmitField('BUY', widget=InlineButtonWidget(class_="btn btn-success pull-right"),
                         render_kw={'name': 'action'})

app/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_wtf.csrf import CSRFProtect

from config import app_config

db = SQLAlchemy()


def create_app(config_name):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(app_config[config_name])
    app.config.from_pyfile('config.py')
    db.init_app(app)
    Migrate(app, db)
    Bootstrap(app)
    CSRFProtect(app)

    from app import models

    from .home import home as home_blueprint
    app.register_blueprint(home_blueprint)

    return app

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
import datetime

from flask import render_template, jsonify, json, request, redirect, url_for, session
from sqlalchemy import desc

from app import db
from app.home.forms import TradeForm
from app.models import Stock, Trade
from app.utils import stockcal
from app.utils.datadump import TradeStats
from . import home

FEES = {'ssi': 0.0025, 'tax': 0.001}
RISK_REWARD = 3


@home.route('/', methods=['GET', 'POST'])
def index():
    models = Stock.query.all()
    dump_stocks = [m.dump() for m in models]

    sold_trades = Trade.query.filter_by(order=0).all()    
    stats = TradeStats(sold_trades).to_dict()

    for s in dump_stocks:
        if s.get('freeroll'):
            s['stop'] = s.get('price') * 1.02
        else:
            s['target'], s['stop'] = stockcal.take_and_stop(s.get('price'), s.get('ratio'), RISK_REWARD)

    form = TradeForm()
    if form.validate_on_submit():
        exist = Stock.query.filter_by(symbol=form.symbol.data.upper()).first()  # type:Stock

        if request.form['action'] == 'BUY':
            # Action: BUY

            # New a trade with buy action
            trade = Trade(
                symbol=form.symbol.data.upper(),
                matched_price=form.price.data,
                net_price=stockcal.net_price(form.price.data, 'buy'),
                shares=form.shares.data,
                order=1,
            ).create()

            if not exist:
                # Create stock if not exists
                Stock(
                    symbol=form.symbol.data.upper(),
                    price=trade.net_price,
                    shares=form.shares.data,
                    ratio=form.profit_margin.data
                ).create()

            else:
                exist.shares = exist.shares + form.shares.data
                # AP = SUM(Pn*Qn)/SUM(Qn)
                exist.price = stockcal.avg_price(exist.price, exist.shares, trade.net_price, trade.shares)
                if form.profit_margin.data:
                    exist.ratio = form.profit_margin.data
                exist.create()
            session['toast'] = '{} has purchased'.format(trade.symbol)
            return redirect(url_for('home.index'))
        elif request.form['action'] == 'SELL':
            # Action: SELL
            # Assert that stock exists and total shares for sale is less than or equal the holding shares
            if not exist:
                form.symbol.errors.append('{} is not holding '.format(form.symbol.data.upper()))

            elif form.shares.data <= exist.shares:
                # New a trade with sell action
                Trade(
                    symbol=form.symbol.data.upper(),
                    matched_price=form.price.data,
                    average_price=exist.price,
                    net_price=stockcal.net_price(form.price.data, 'sell'),
                    shares=form.shares.data,
                    order=0,
                ).create()

                exist.shares = exist.shares - form.shares.data
                if exist.shares > 0:
                    exist.create()
                else:
                    # Delete if holding shares is equal to 0
                    db.session.delete(exist)
                    db.session.commit()
                session['toast'] = '{} has sold'.format(exist.symbol)
                return redirect(url_for('home.index'))
            else:
                form.shares.errors.append('Shares for sale is less than or equal to {}'.format(exist.shares))

    elif request.form.get('name') == 'freeroll':
        # handle Checkbox
        id = request.form.get('value')
        s = Stock.query.get(id)  # type:Stock
        s.freeroll = int(request.form.get('checked')) > 0
        s.create()
        tp, sl = stockcal.take_and_stop(s.price, s.ratio, RISK_REWARD)
        obj = {
            'target-' + id: 'FREE' if s.freeroll else tp,
            'stop-' + id: s.price * 1.02 if s.freeroll else sl
        }
        return jsonify(json.dumps(obj, ensure_ascii=False))
    elif form.errors:
        data = json.dumps(form.errors, ensure_ascii=False)
        return jsonify(data)

    return render_template('home/index.html', stocks=dump_stocks, form=form, stats=stats)


@home.route('/history', methods=['GET'])
def history():
    trades = Trade.query.order_by(desc(Trade.date)).all()
    dump_data = [t.dump() for t in trades]
    for t in dump_data:
        t['gross_amount'] = t.get('shares') * t.get('matched_price')
        t['amount'] = t.get('shares') * t.get('net_price')
        t['date'] = datetime.datetime.strptime(t.get('date'), '%Y-%m-%dT%H:%M:%S')
        if t.get('order') == 0:
            t['percent'] = stockcal.profit_percent(t.get('average_price'), t.get('net_price'))
            t['gain_loss'] = t.get('percent') * t.get('average_price') * t.get('shares')
            t['fees'] = t.get('gross_amount') * (FEES['ssi'] + FEES['tax'])
        else:
            t['fees'] = t.get('gross_amount') * FEES['ssi']

    return render_template('home/history.html', trades=dump_data)

app/templates/home/history.html
{% extends "layout/base.html" %}
{% block styles %}
    <!-- DataTables CSS -->
    <link rel="stylesheet" href="{{ url_for('static',filename='css/dataTables/dataTables.bootstrap.css') }}">

    <!-- DataTables Responsive CSS -->
    <link rel="stylesheet" href="{{ url_for('static',filename='css/dataTables/dataTables.responsive.css') }}">
{% endblock %}
{% block scripts %}
    <!-- DataTables JavaScript -->
    <script src="{{ url_for('static',filename='js/dataTables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/dataTables/dataTables.bootstrap.min.js') }}"></script>
    <script>
        $(document).ready(function () {
            <!-- Tables - Use for reference -->
            $('#stockTable').DataTable({
                responsive: true,
                lengthChange: false,
                order: [],
            });
        });
    </script>
{% endblock %}
{% block title %}History{% endblock %}
{% block ptitle %}History{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-history"></i> Trade History
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover" id="stockTable">
                            <thead>
                            <tr>
                                <th>Date(dd/mm/yyyy)</th>
                                <th>Symbol</th>
                                <th>Action</th>
                                <th>MP</th>
                                <th>Shares</th>
                                <th>Gross Amount</th>
                                <th>Total Fees</th>
                                <th>NP</th>
                                <th>Amount</th>
                                <th>AP</th>
                                <th>Gain/Loss</th>
                                <th>Gain/Loss (%)</th>
                            </tr>
                            </thead>
                            <tbody>
                            <form action="{{ url_for('.index') }}" method="post">
                                {% for  t in trades %}
                                    <tr>
                                        <td>{{ t.date.strftime('%d/%m/%Y') }}</td>
                                        <td>{{ t.symbol }}</td>
                                        <td>
                                            <span class="{{ 'label label-primary' if t.order >0 else 'label label-danger' }}">
                                                {% if t.order > 0 %}BUY{% else %}SELL{% endif %}
                                            </span>
                                        </td>
                                        <td>{{ "{:,.2f}".format(t.matched_price) }}</td>
                                        <td>{{ "{:,.0f}".format(t.shares) }}</td>
                                        <td>{{ "{:,.0f}".format(t.gross_amount) }}</td>
                                        <td>{{ "{:,.0f}".format(t.fees) }}</td>
                                        <td>{{ "{:,.2f}".format(t.net_price) }}</td>
                                        <td>{{ "{:,.0f}".format(t.amount) }}</td>
                                        <td>{% if t.average_price %}
                                            {{ "{:,.2f}".format(t.average_price) }}{% endif %}</td>
                                        <td {% if t.gain_loss %}class="{{ 'text-primary' if t.gain_loss>0 else 'text-danger' }}" {% endif %}>
                                            {% if t.gain_loss %}{{ "{:,.0f}".format(t.gain_loss) }}{% endif %}</td>
                                        <td {% if t.percent %}class="{{ 'text-primary' if t.percent>0 else 'text-danger' }}" {% endif %}>
                                            {% if t.percent %}{{ "{:,.2f}".format(t.percent*100) }}{% endif %}</td>
                                    </tr>
                                {% endfor %}
                            </form>
                            </tbody>
                        </table>
                    </div>
                    <!-- /.table-responsive -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
    </div>
{% endblock %}

app/templates/home/index.html
{% extends "layout/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles %}
    <!-- DataTables CSS -->
    <link rel="stylesheet" href="{{ url_for('static',filename='css/dataTables/dataTables.bootstrap.css') }}">

    <!-- DataTables Responsive CSS -->
    <link rel="stylesheet" href="{{ url_for('static',filename='css/dataTables/dataTables.responsive.css') }}">

    <!-- Donut Chart CSS -->
    <link rel="stylesheet" href="{{ url_for('static',filename='css/percircle.css') }}">

{% endblock %}
{% block meta %}
    <meta name="csrf-token" content="{{ csrf_token() }}">
{% endblock %}

{% block scripts %}
    <!-- DataTables JavaScript -->
    <script src="{{ url_for('static',filename='js/dataTables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/dataTables/dataTables.bootstrap.min.js') }}"></script>

    <!-- Donut Chart JS -->
    <script src="{{ url_for('static',filename='js/percircle.js') }}"></script>

    <!-- Toast JS -->
    <script src="{{ url_for('static',filename='js/toast.min.js') }}"></script>

    <!-- App Javascript -->
    <script src="{{ url_for('static',filename='js/utils.js') }}"></script>


{% endblock %}
{% block finally_scripts %}

    <script>
        $(document).ready(function () {
            <!-- Tables - Use for reference -->
            $('#stockTable').DataTable({
                responsive: true,
                lengthChange: false,
                order: [3, 'desc']
            });

            <!-- Ajax -->
            checkboxAjax($('[name="freeroll"]'), '{{ url_for(".index") }}', function (data) {
                let obj = JSON.parse(data);
                for (let key in obj) {
                    if (obj.hasOwnProperty(key)) {
                        $('#' + key).text((typeof obj[key] === 'string') ? obj[key] : obj[key].toFixed(2));
                    }
                }
            });


            <!-- Donut Charts -->
            $("#chartGain").percircle();
            $("#chartLoss").percircle();
            $("#chartWinRate").percircle();

            <!-- Render Toast -->
            let toastMsg = '{{ session.pop("toast") if  session.get("toast") else None}}';
            if (toastMsg !== "None") {
                iqwerty.toast.toast(toastMsg);
            }
        });
    </script>
{% endblock %}
{% block title %}Dashboard{% endblock %}
{% block ptitle %}Dashboard{% endblock %}
{% block content %}
    <!-- /.row -->
    <div class="row">
        {% include "includes/panels/panel_overall.html" %}
    </div>
    <!-- /.row -->
    <div class="row">
        {% include "includes/panels/panel_portfolio.html" %}
        <div class="col-lg-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Trade
                </div>
                <div class="panel-body">
                    <form class="form" action="" role="form" method="post">
                        {{ wtf.quick_form(form) }}
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/includes/panels/panel_overall.html
<div class="col-lg-8">
    <div class="panel panel-info">
        <div class="panel-heading">
            <i class="fa fa-chart-pie"></i> Overall Trade Stats
        </div>
        <div class="panel-body">
            <div class="col-xs-6 col-md-4 text-center">
                <div class="green center" id="chartGain"
                     data-percent="{{ "{:,.2f}".format(stats.gain.rate*100) }}"></div>
                <div class="label-custom text-success"><span class="text-muted">Gain</span>
                    <br> {{ "{:,.2f}".format(stats.gain.profit) }}</div>
            </div>
            <div class="col-xs-6 col-md-4 text-center">
                <div class="red center" id="chartLoss"
                     data-percent="{{ "{:,.2f}".format(stats.loss.rate*100) }}"></div>
                <div class="text-danger label-custom"><span class="text-muted">Loss</span>
                    <br> {{ "{:,.2f}".format( stats.loss.profit) }}</div>
            </div>
            <div class="col-xs-6 col-md-4 text-center">
                <div class="blue center" id="chartWinRate"
                     data-percent="{{ "{:,.2f}".format(stats.win_rate*100) }}"></div>
                <div class="text-muted label-custom">WinRate</div>
            </div>
        </div>
    </div>
</div>
<div>
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                Overall Trade Gain/Loss
            </div>
            <div class="panel-body">
                <div class="list-group">
                    <div class="list-group-item">
                        Trades
                        <span class="pull-right">{{ stats.num_of_trades }}</span></div>
                    {% set profit=stats.gain.profit - stats.loss.profit %}
                    <div class="list-group-item">
                        Largest Gain
                        <span class="pull-right text-primary">
                            {{ "{:,.2f}".format(stats.gain.largest) }}
                        </span>
                    </div>
                    <div class="list-group-item">
                        Largest Loss
                        <span class="pull-right text-danger">
                            {{ "{:,.2f}".format(stats.loss.largest) }}
                        </span>
                    </div>
                    <div class="list-group-item">
                        Gross Profit
                        <span class="pull-right {{ 'text-primary' if profit > 0 else 'text-danger' }}">
                            {{ "{:,.2f}".format(profit) }}
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/templates/includes/panels/panel_portfolio.html
<div class="col-lg-8">
    <div class="panel panel-default">
        <div class="panel-heading">
            <i class="fa fa-chart-simple"></i> Stock Position
        </div>

        <!-- /.panel-heading -->
        <div class="panel-body">

            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover" id="stockTable">
                    <thead>
                    <tr>
                        <th>Symbol</th>
                        <th>Avg. Price</th>
                        <th>Shares</th>
                        <th>Amount</th>
                        <th>Profit Margin (%)</th>
                        <th>Target Price</th>
                        <th>Stop Loss</th>
                        <th class="text-center">Freeroll</th>

                    </tr>
                    </thead>
                    <tbody>
                    <form action="{{ url_for('.index') }}" method="post">
                        {% for  s in stocks %}
                            <tr>
                                <td>{{ s.symbol }}</td>
                                <td class="text-primary">{{ "{:,.2f}".format(s.price) }}</td>
                                <td>{{ "{:,.0f}".format(s.shares) }}</td>
                                <td>{{ "{:,.0f}".format(s.price*s.shares) }}</td>
                                <td>{{ "{:,.0f}".format( s.ratio*100) }}</td>
                                <td id="target-{{ s.id }}">
                                    {% if s.target %}{{ "{:,.2f}".format(s.target) }}{% else %}
                                        <span>FREE</span>{% endif %}</td>
                                <td id="stop-{{ s.id }}">{{ "{:,.2f}".format(s.stop) }}</td>
                                <td class="text-center">
                                    <label>
                                        <input type="checkbox" name="freeroll" value="{{ s.id }}"
                                               {% if s.freeroll %}checked{% endif %}>
                                    </label>
                                </td>
                            </tr>
                        {% endfor %}
                    </form>
                    </tbody>
                </table>
            </div>
            <!-- /.table-responsive -->
        </div>
        <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
</div>

app/templates/includes/sidebar.html
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">

        <ul class="nav" id="side-menu">
            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Search...">
                    <span class="input-group-btn">
                                    <button class="btn btn-primary" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                </div>
            </li>
            <li>
                <a href="{{ url_for('home.index') }}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
            </li>
            <li>
                <a href="{{ url_for('home.history') }}"><i class="fa fa-history fa-fw"></i> Trade History</a>
            </li>
        </ul>

    </div>
</div>

app/templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block meta %}{% endblock %}

    <title>Portfolio - {% block title %}{% endblock %}</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{ url_for('static',filename='css/bootstrap.min.css') }}" rel="stylesheet">


    <!-- MetisMenu CSS -->
    <link href="{{ url_for('static',filename='css/metisMenu.min.css') }}" rel="stylesheet">

    {% block styles %}{% endblock %}

    <!-- Custom CSS -->
    <link href="{{ url_for('static',filename='css/style.css') }}" rel="stylesheet">
    <link href="{{ url_for('static',filename='css/app.css') }}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{{ url_for('static',filename='css/all.min.css') }}" rel="stylesheet">


</head>
<body>

<div id="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ url_for('home.index') }}">Portfolio</a>
        </div>

        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>

        <!-- Sidebar -->
        {% include 'includes/sidebar.html' %}

    </nav>

    <!-- Page Content -->
    <div id="page-wrapper">
        <div class="container-fluid">

            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">{% block ptitle %}{% endblock %}</h1>
                </div>
            </div>

            <!-- ... Your content goes here ... -->
            {% block content %}{% endblock %}

        </div>
    </div>

</div>

<!-- jQuery -->
<script src="{{ url_for('static',filename='js/jquery.min.js') }}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{{ url_for('static',filename='js/bootstrap.min.js') }}"></script>


<!-- Metis Menu Plugin JavaScript -->
<script src="{{ url_for('static',filename='js/metisMenu.min.js') }}"></script>

{% block scripts %}{% endblock %}

<!-- Custom Theme JavaScript -->
<script src="{{ url_for('static',filename='js/main.js') }}"></script>


{% block finally_scripts %}{% endblock %}
</body>
</html>